// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hashfun_1
Rcpp::IntegerVector hashfun_1(IntegerVector vec);
RcppExport SEXP LSHR_hashfun_1(SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type vec(vecSEXP);
    __result = Rcpp::wrap(hashfun_1(vec));
    return __result;
END_RCPP
}
// get_minhash_matrix
IntegerVector get_minhash_matrix(int unique_shingles_length, uint32_t hashfun_number, uint32_t seed);
RcppExport SEXP LSHR_get_minhash_matrix(SEXP unique_shingles_lengthSEXP, SEXP hashfun_numberSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type unique_shingles_length(unique_shingles_lengthSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type hashfun_number(hashfun_numberSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type seed(seedSEXP);
    __result = Rcpp::wrap(get_minhash_matrix(unique_shingles_length, hashfun_number, seed));
    return __result;
END_RCPP
}
