// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// get_hash_matrix
IntegerMatrix get_hash_matrix(int unique_shingles_length, int hashfun_number, int cores);
RcppExport SEXP LSHR_get_hash_matrix(SEXP unique_shingles_lengthSEXP, SEXP hashfun_numberSEXP, SEXP coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type unique_shingles_length(unique_shingles_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type hashfun_number(hashfun_numberSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    __result = Rcpp::wrap(get_hash_matrix(unique_shingles_length, hashfun_number, cores));
    return __result;
END_RCPP
}
