# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hashfun_1 <- function(vec, cores = 2L) {
    .Call('LSHR_hashfun_1', PACKAGE = 'LSHR', vec, cores)
}

#' @export
get_hash_matrix <- function(unique_shingles_length, hashfun_number = 60L, cores = 2L) {
    .Call('LSHR_get_hash_matrix', PACKAGE = 'LSHR', unique_shingles_length, hashfun_number, cores)
}

get_tdm_character <- function(sets) {
    .Call('LSHR_get_tdm_character', PACKAGE = 'LSHR', sets)
}

get_tdm_integer <- function(sets) {
    .Call('LSHR_get_tdm_integer', PACKAGE = 'LSHR', sets)
}

